### ISSUE TITLE
[PE-D][Tester D] fitadd Command Accepts /armarmarm as /arm

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T17-3/tp#262] opened 2024-04-05 19:08 UTC
Not sure whether this is an intended behaviour.
fitadd 1 /armarmarm 
results in the same output as 
fitadd 1 /arm

similarly,
fitted 1 /armlegs
results in the same output as 
fitadd 1 /arm

Perhaps an exact String matching (i.e. only /arm is accepted but not the others) could serve the functionality better?

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: wang-xinrong/ped#7

**Comment by jjchee77** [comment] 2024-04-08 08:31
This issue is caused by the way `FitAddCommandParser.java` and `FitDeleteCommandParser.java` checks for the default supported prefixes (ie. `/all`, `/arms`, `/legs` etc.).

It currently simply uses the `contains` method from the `ArgumentMultimap` class to check for default supported prefixes. Therefore, text supplied after the default supported prefixes (until the next prefix) will be regarded as the "argument's value".

Unless it violates the feature freeze, the proposed solution is to implement an additional check to ensure that the "argument's value" is empty to enforce that the user-supplied command must adhere to the current command format.

**Comment by dillontkh** [comment] 2024-04-08 13:10
dupe of #292

**Closed by dillontkh** 2024-04-08 13:10 UTC
Labels: triage.InProgress
